Make the convertToUpperCase() regex compatible with Safari
Like John found,
there was an error in Safari, and the app crashed:
SyntaxError: Invalid regular expression: invalid group specifier name

This is from a lookbehind, which Safari doesn't support.